version: "3"

services:
  web:
    build: .
    restart: always
    environment:
      ENV: prod
    volumes:
      - ./data/db:/app/data/db
      - ./sounds:/app/sounds
      - ./conf/secrets.conf:/app/conf/secrets.conf
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    expose:
      - 80
    depends_on:
      - web
    ports:
      - 8000:80
    #networks:
    #  - default
    #  - web
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.goffredo.rule=Host(`goffredobot.xyz`)
    #  - traefik.http.routers.goffredo.tls=true

#networks:
#  web:
#    external: true
