version: "3"

services:
  web:
    build: .
    environment:
      ENV: prod
    volumes:
      - ./data/db:/app/data/db
      - ./sounds:/app/sounds
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.goffredo.rule=Host(`goffredobot.xyz`)
      - traefik.http.routers.goffredo.tls=true

networks:
  web:
    external: true
