name: Build and push Goffredo container image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  GOFFREDO_IMAGE_NAME: goffredo
  PROXY_IMAGE_NAME: goffredo-proxy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Goffredo
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.GOFFREDO_IMAGE_NAME }}:latest
          
      - name: Build and push proxy
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          file: Dockerfile.nginx
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PROXY_IMAGE_NAME }}:latest
